"""init-baseline

Revision ID: 0bd5556acb4c
Revises: 
Create Date: 2026-08-22 21:15:00.539023

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bd5556acb4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('omega_miya_artwork_collection',
                    sa.Column('origin', sa.String(length=64), nullable=False, comment='作品来源/收录该作品的站点'),
                    sa.Column('aid', sa.String(length=64), nullable=False, comment='作品原始ID/收录该作品的站点索引ID'),
                    sa.Column('title', sa.String(length=255), nullable=False, comment='作品标题title'),
                    sa.Column('uid', sa.String(length=255), nullable=False, comment='作者uid'),
                    sa.Column('uname', sa.String(length=255), nullable=False, comment='作者名'),
                    sa.Column('classification', sa.Integer(), nullable=False,
                              comment='标记标签, -2=忽略, -1=未知, 0=未分类, 1=AI生成, 2=外部来源, 3=人工分类'),
                    sa.Column('rating', sa.Integer(), nullable=False,
                              comment='分级标签, -1=Unknown, 0=G, 1=S, 2=Q, 3=E'),
                    sa.Column('width', sa.Integer(), nullable=False, comment='原始图片宽度'),
                    sa.Column('height', sa.Integer(), nullable=False, comment='原始图片高度'),
                    sa.Column('tags', sa.String(length=4096), nullable=False, comment='作品标签'),
                    sa.Column('description', sa.String(length=4096), nullable=True, comment='作品描述'),
                    sa.Column('source', sa.String(length=1024), nullable=False, comment='作品原始出处地址'),
                    sa.Column('cover_page', sa.String(length=1024), nullable=False, comment='作品首页/封面原图链接'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('origin', 'aid', name=op.f('pk_omega_miya_artwork_collection'))
                    )
    op.create_index(op.f('ix_omega_miya_artwork_collection_aid'), 'omega_miya_artwork_collection', ['aid'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_artwork_collection_classification'), 'omega_miya_artwork_collection',
                    ['classification'], unique=False)
    op.create_index(op.f('ix_omega_miya_artwork_collection_height'), 'omega_miya_artwork_collection', ['height'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_artwork_collection_origin'), 'omega_miya_artwork_collection', ['origin'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_artwork_collection_rating'), 'omega_miya_artwork_collection', ['rating'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_artwork_collection_title'), 'omega_miya_artwork_collection', ['title'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_artwork_collection_uid'), 'omega_miya_artwork_collection', ['uid'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_artwork_collection_uname'), 'omega_miya_artwork_collection', ['uname'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_artwork_collection_width'), 'omega_miya_artwork_collection', ['width'],
                    unique=False)
    op.create_table('omega_miya_bots',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('self_id', sa.String(length=64), nullable=False,
                              comment='bot身份id, 用于识别bot, qq号等'),
                    sa.Column('bot_type', sa.String(length=64), nullable=False, comment='Bot类型, 具体使用的协议'),
                    sa.Column('bot_status', sa.Integer(), nullable=False, comment='Bot在线状态'),
                    sa.Column('bot_info', sa.String(length=512), nullable=True, comment='Bot描述信息'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_bots'))
                    )
    op.create_index(op.f('ix_omega_miya_bots_bot_type'), 'omega_miya_bots', ['bot_type'], unique=False)
    op.create_index(op.f('ix_omega_miya_bots_id'), 'omega_miya_bots', ['id'], unique=True)
    op.create_index(op.f('ix_omega_miya_bots_self_id'), 'omega_miya_bots', ['self_id'], unique=True)
    op.create_table('omega_miya_global_cache',
                    sa.Column('cache_name', sa.String(length=64), nullable=False),
                    sa.Column('cache_key', sa.String(length=64), nullable=False),
                    sa.Column('cache_value', sa.String(length=4096), nullable=False),
                    sa.Column('expired_at', sa.DateTime(), nullable=False, comment='缓存到期时间'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('cache_name', 'cache_key', name=op.f('pk_omega_miya_global_cache'))
                    )
    op.create_index(op.f('ix_omega_miya_global_cache_cache_key'), 'omega_miya_global_cache', ['cache_key'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_global_cache_cache_name'), 'omega_miya_global_cache', ['cache_name'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_global_cache_expired_at'), 'omega_miya_global_cache', ['expired_at'],
                    unique=False)
    op.create_table('omega_miya_message_history',
                    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(),
                                                                                                       'postgresql').with_variant(
                        sa.INTEGER(), 'sqlite'), nullable=False),
                    sa.Column('message_id', sa.String(length=64), nullable=False, comment='消息ID'),
                    sa.Column('bot_self_id', sa.String(length=64), nullable=False, comment='收到消息的机器人ID'),
                    sa.Column('event_entity_id', sa.String(length=64), nullable=False, comment='消息事件实体ID'),
                    sa.Column('user_entity_id', sa.String(length=64), nullable=False, comment='发送对象实体ID'),
                    sa.Column('received_time', sa.BigInteger(), nullable=False, comment='收到消息事件的时间戳'),
                    sa.Column('message_type', sa.String(length=64), nullable=False, comment='消息事件类型'),
                    sa.Column('message_raw', sa.String(length=4096), nullable=False, comment='原始消息数据'),
                    sa.Column('message_text', sa.String(length=4096), nullable=False, comment='经处理的消息文本内容'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_message_history'))
                    )
    op.create_index(op.f('ix_omega_miya_message_history_bot_self_id'), 'omega_miya_message_history', ['bot_self_id'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_message_history_event_entity_id'), 'omega_miya_message_history',
                    ['event_entity_id'], unique=False)
    op.create_index(op.f('ix_omega_miya_message_history_id'), 'omega_miya_message_history', ['id'], unique=True)
    op.create_index(op.f('ix_omega_miya_message_history_message_id'), 'omega_miya_message_history', ['message_id'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_message_history_message_type'), 'omega_miya_message_history', ['message_type'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_message_history_received_time'), 'omega_miya_message_history',
                    ['received_time'], unique=False)
    op.create_index(op.f('ix_omega_miya_message_history_user_entity_id'), 'omega_miya_message_history',
                    ['user_entity_id'], unique=False)
    op.create_table('omega_miya_plugin',
                    sa.Column('plugin_name', sa.String(length=64), nullable=False),
                    sa.Column('module_name', sa.String(length=128), nullable=False),
                    sa.Column('enabled', sa.Integer(), nullable=False,
                              comment='启用状态, 1: 启用, 0: 禁用, -1: 失效或未安装'),
                    sa.Column('info', sa.String(length=255), nullable=True, comment='插件信息及附加说明'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('plugin_name', 'module_name', name=op.f('pk_omega_miya_plugin'))
                    )
    op.create_index(op.f('ix_omega_miya_plugin_enabled'), 'omega_miya_plugin', ['enabled'], unique=False)
    op.create_index(op.f('ix_omega_miya_plugin_module_name'), 'omega_miya_plugin', ['module_name'], unique=True)
    op.create_index(op.f('ix_omega_miya_plugin_plugin_name'), 'omega_miya_plugin', ['plugin_name'], unique=True)
    op.create_table('omega_miya_social_media_content',
                    sa.Column('source', sa.String(length=64), nullable=False, comment='出处平台'),
                    sa.Column('m_id', sa.String(length=64), nullable=False, comment='内容原始ID'),
                    sa.Column('m_type', sa.String(length=64), nullable=False, comment='内容原始类型'),
                    sa.Column('m_uid', sa.String(length=64), nullable=False, comment='内容发布者ID'),
                    sa.Column('title', sa.String(length=255), nullable=False, comment='内容标题'),
                    sa.Column('content', sa.String(length=4096), nullable=False, comment='内容文本'),
                    sa.Column('ref_content', sa.String(length=4096), nullable=True, comment='引用/转发内容文本'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('source', 'm_id', name=op.f('pk_omega_miya_social_media_content'))
                    )
    op.create_index(op.f('ix_omega_miya_social_media_content_m_id'), 'omega_miya_social_media_content', ['m_id'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_social_media_content_m_type'), 'omega_miya_social_media_content', ['m_type'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_social_media_content_m_uid'), 'omega_miya_social_media_content', ['m_uid'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_social_media_content_source'), 'omega_miya_social_media_content', ['source'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_social_media_content_title'), 'omega_miya_social_media_content', ['title'],
                    unique=False)
    op.create_table('omega_miya_statistic',
                    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(),
                                                                                                       'postgresql').with_variant(
                        sa.INTEGER(), 'sqlite'), nullable=False),
                    sa.Column('module_name', sa.String(length=128), nullable=False, comment='插件模块名称'),
                    sa.Column('plugin_name', sa.String(length=64), nullable=False, comment='插件显示名称'),
                    sa.Column('bot_self_id', sa.String(length=64), nullable=False, comment='对应的Bot'),
                    sa.Column('parent_entity_id', sa.String(length=64), nullable=False,
                              comment='对应调用用户父实体信息'),
                    sa.Column('entity_id', sa.String(length=64), nullable=False, comment='对应调用用户实体信息'),
                    sa.Column('call_time', sa.DateTime(), nullable=False, comment='调用时间'),
                    sa.Column('call_info', sa.String(length=4096), nullable=True, comment='调用信息'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_statistic'))
                    )
    op.create_index(op.f('ix_omega_miya_statistic_bot_self_id'), 'omega_miya_statistic', ['bot_self_id'], unique=False)
    op.create_index(op.f('ix_omega_miya_statistic_call_time'), 'omega_miya_statistic', ['call_time'], unique=False)
    op.create_index(op.f('ix_omega_miya_statistic_entity_id'), 'omega_miya_statistic', ['entity_id'], unique=False)
    op.create_index(op.f('ix_omega_miya_statistic_id'), 'omega_miya_statistic', ['id'], unique=True)
    op.create_index(op.f('ix_omega_miya_statistic_module_name'), 'omega_miya_statistic', ['module_name'], unique=False)
    op.create_index(op.f('ix_omega_miya_statistic_parent_entity_id'), 'omega_miya_statistic', ['parent_entity_id'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_statistic_plugin_name'), 'omega_miya_statistic', ['plugin_name'], unique=False)
    op.create_table('omega_miya_subscription_source',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sub_type', sa.String(length=64), nullable=False, comment='订阅类型'),
                    sa.Column('sub_id', sa.String(length=64), nullable=False, comment='订阅id，直播间房间号/用户uid等'),
                    sa.Column('sub_user_name', sa.String(length=64), nullable=False, comment='订阅用户的名称'),
                    sa.Column('sub_info', sa.String(length=64), nullable=True, comment='订阅源信息'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_subscription_source'))
                    )
    op.create_index(op.f('ix_omega_miya_subscription_source_id'), 'omega_miya_subscription_source', ['id'], unique=True)
    op.create_index(op.f('ix_omega_miya_subscription_source_sub_id'), 'omega_miya_subscription_source', ['sub_id'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_subscription_source_sub_type'), 'omega_miya_subscription_source', ['sub_type'],
                    unique=False)
    op.create_table('omega_miya_system_setting',
                    sa.Column('setting_name', sa.String(length=64), nullable=False),
                    sa.Column('setting_key', sa.String(length=64), nullable=False),
                    sa.Column('setting_value', sa.String(length=255), nullable=False, comment='参数值'),
                    sa.Column('info', sa.String(length=64), nullable=True, comment='参数说明'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('setting_name', 'setting_key', name=op.f('pk_omega_miya_system_setting'))
                    )
    op.create_index(op.f('ix_omega_miya_system_setting_setting_key'), 'omega_miya_system_setting', ['setting_key'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_system_setting_setting_name'), 'omega_miya_system_setting', ['setting_name'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_system_setting_setting_value'), 'omega_miya_system_setting', ['setting_value'],
                    unique=False)
    op.create_table('omega_miya_word_bank',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('key_word', sa.String(length=128), nullable=False, comment='匹配目标'),
                    sa.Column('reply_entity', sa.String(length=64), nullable=False,
                              comment='响应对象, 可为群号/用户qq/频道id等标识'),
                    sa.Column('result_word', sa.String(length=4096), nullable=False, comment='结果文本'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_word_bank'))
                    )
    op.create_index(op.f('ix_omega_miya_word_bank_id'), 'omega_miya_word_bank', ['id'], unique=True)
    op.create_index(op.f('ix_omega_miya_word_bank_key_word'), 'omega_miya_word_bank', ['key_word'], unique=False)
    op.create_index(op.f('ix_omega_miya_word_bank_reply_entity'), 'omega_miya_word_bank', ['reply_entity'],
                    unique=False)
    op.create_table('omega_miya_entity',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('bot_index_id', sa.Integer(), nullable=False, comment='所属bot'),
                    sa.Column('entity_id', sa.String(length=64), nullable=False,
                              comment='实体身份id, 不同类型实体可能相同, qq号/群号等'),
                    sa.Column('entity_type', sa.String(length=64), nullable=False, comment='实体类型'),
                    sa.Column('parent_id', sa.String(length=64), nullable=False, comment='父实体id, qq号/群号等'),
                    sa.Column('entity_name', sa.String(length=64), nullable=False, comment='实体名称'),
                    sa.Column('entity_info', sa.String(length=512), nullable=True, comment='实体描述信息'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['bot_index_id'], ['omega_miya_bots.id'],
                                            name=op.f('fk_omega_miya_entity_bot_index_id_omega_miya_bots'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_entity'))
                    )
    op.create_index(op.f('ix_omega_miya_entity_entity_id'), 'omega_miya_entity', ['entity_id'], unique=False)
    op.create_index(op.f('ix_omega_miya_entity_entity_name'), 'omega_miya_entity', ['entity_name'], unique=False)
    op.create_index(op.f('ix_omega_miya_entity_entity_type'), 'omega_miya_entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_omega_miya_entity_id'), 'omega_miya_entity', ['id'], unique=True)
    op.create_index(op.f('ix_omega_miya_entity_parent_id'), 'omega_miya_entity', ['parent_id'], unique=False)
    op.create_table('omega_miya_auth_setting',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('entity_index_id', sa.Integer(), nullable=False),
                    sa.Column('module', sa.String(length=64), nullable=False, comment='模块名'),
                    sa.Column('plugin', sa.String(length=64), nullable=False, comment='插件名'),
                    sa.Column('node', sa.String(length=64), nullable=False, comment='权限节点/配置名'),
                    sa.Column('available', sa.Integer(), nullable=False,
                              comment='需求值, 0=deny/disable, 1=allow/enable, 1<=level'),
                    sa.Column('value', sa.String(length=4096), nullable=True,
                              comment='若为插件配置项且对象具有的配置信息'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'],
                                            name=op.f('fk_omega_miya_auth_setting_entity_index_id_omega_miya_entity'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_auth_setting'))
                    )
    op.create_index(op.f('ix_omega_miya_auth_setting_available'), 'omega_miya_auth_setting', ['available'],
                    unique=False)
    op.create_index(op.f('ix_omega_miya_auth_setting_id'), 'omega_miya_auth_setting', ['id'], unique=True)
    op.create_index(op.f('ix_omega_miya_auth_setting_module'), 'omega_miya_auth_setting', ['module'], unique=False)
    op.create_index(op.f('ix_omega_miya_auth_setting_node'), 'omega_miya_auth_setting', ['node'], unique=False)
    op.create_index(op.f('ix_omega_miya_auth_setting_plugin'), 'omega_miya_auth_setting', ['plugin'], unique=False)
    op.create_table('omega_miya_cooldown',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('entity_index_id', sa.Integer(), nullable=False),
                    sa.Column('event', sa.String(length=64), nullable=False,
                              comment='冷却事件, 用于唯一标识某个/类冷却'),
                    sa.Column('stop_at', sa.DateTime(), nullable=False, comment='冷却结束时间'),
                    sa.Column('description', sa.String(length=128), nullable=True, comment='事件描述'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'],
                                            name=op.f('fk_omega_miya_cooldown_entity_index_id_omega_miya_entity'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_cooldown'))
                    )
    op.create_index(op.f('ix_omega_miya_cooldown_event'), 'omega_miya_cooldown', ['event'], unique=False)
    op.create_index(op.f('ix_omega_miya_cooldown_id'), 'omega_miya_cooldown', ['id'], unique=True)
    op.create_index(op.f('ix_omega_miya_cooldown_stop_at'), 'omega_miya_cooldown', ['stop_at'], unique=False)
    op.create_table('omega_miya_friendship',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('entity_index_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=64), nullable=False, comment='当前状态'),
                    sa.Column('mood', sa.Float(), nullable=False, comment='情绪值, 大于0: 好心情, 小于零: 坏心情'),
                    sa.Column('friendship', sa.Float(), nullable=False,
                              comment='好感度/亲密度, 大于0: 友好, 小于0: 厌恶'),
                    sa.Column('energy', sa.Float(), nullable=False, comment='能量值'),
                    sa.Column('currency', sa.Float(), nullable=False, comment='持有货币'),
                    sa.Column('response_threshold', sa.Float(), nullable=False,
                              comment='响应阈值, 控制对交互做出响应的概率或频率, 根据具体插件使用数值'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'],
                                            name=op.f('fk_omega_miya_friendship_entity_index_id_omega_miya_entity'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_friendship')),
                    sa.UniqueConstraint('entity_index_id', name=op.f('uq_omega_miya_friendship_entity_index_id'))
                    )
    op.create_index(op.f('ix_omega_miya_friendship_id'), 'omega_miya_friendship', ['id'], unique=True)
    op.create_table('omega_miya_sign_in',
                    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(),
                                                                                                       'postgresql').with_variant(
                        sa.INTEGER(), 'sqlite'), nullable=False),
                    sa.Column('entity_index_id', sa.Integer(), nullable=False),
                    sa.Column('sign_in_date', sa.Date(), nullable=False, comment='签到日期'),
                    sa.Column('sign_in_info', sa.String(length=64), nullable=True, comment='签到信息'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'],
                                            name=op.f('fk_omega_miya_sign_in_entity_index_id_omega_miya_entity'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_sign_in'))
                    )
    op.create_index(op.f('ix_omega_miya_sign_in_id'), 'omega_miya_sign_in', ['id'], unique=True)
    op.create_index(op.f('ix_omega_miya_sign_in_sign_in_date'), 'omega_miya_sign_in', ['sign_in_date'], unique=False)
    op.create_table('omega_miya_subscription',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sub_source_index_id', sa.Integer(), nullable=False),
                    sa.Column('entity_index_id', sa.Integer(), nullable=False),
                    sa.Column('sub_info', sa.String(length=64), nullable=True, comment='订阅信息'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'],
                                            name=op.f('fk_omega_miya_subscription_entity_index_id_omega_miya_entity'),
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['sub_source_index_id'], ['omega_miya_subscription_source.id'], name=op.f(
                        'fk_omega_miya_subscription_sub_source_index_id_omega_miya_subscription_source'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_subscription'))
                    )
    op.create_index(op.f('ix_omega_miya_subscription_id'), 'omega_miya_subscription', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_omega_miya_subscription_id'), table_name='omega_miya_subscription')
    op.drop_table('omega_miya_subscription')
    op.drop_index(op.f('ix_omega_miya_sign_in_sign_in_date'), table_name='omega_miya_sign_in')
    op.drop_index(op.f('ix_omega_miya_sign_in_id'), table_name='omega_miya_sign_in')
    op.drop_table('omega_miya_sign_in')
    op.drop_index(op.f('ix_omega_miya_friendship_id'), table_name='omega_miya_friendship')
    op.drop_table('omega_miya_friendship')
    op.drop_index(op.f('ix_omega_miya_cooldown_stop_at'), table_name='omega_miya_cooldown')
    op.drop_index(op.f('ix_omega_miya_cooldown_id'), table_name='omega_miya_cooldown')
    op.drop_index(op.f('ix_omega_miya_cooldown_event'), table_name='omega_miya_cooldown')
    op.drop_table('omega_miya_cooldown')
    op.drop_index(op.f('ix_omega_miya_auth_setting_plugin'), table_name='omega_miya_auth_setting')
    op.drop_index(op.f('ix_omega_miya_auth_setting_node'), table_name='omega_miya_auth_setting')
    op.drop_index(op.f('ix_omega_miya_auth_setting_module'), table_name='omega_miya_auth_setting')
    op.drop_index(op.f('ix_omega_miya_auth_setting_id'), table_name='omega_miya_auth_setting')
    op.drop_index(op.f('ix_omega_miya_auth_setting_available'), table_name='omega_miya_auth_setting')
    op.drop_table('omega_miya_auth_setting')
    op.drop_index(op.f('ix_omega_miya_entity_parent_id'), table_name='omega_miya_entity')
    op.drop_index(op.f('ix_omega_miya_entity_id'), table_name='omega_miya_entity')
    op.drop_index(op.f('ix_omega_miya_entity_entity_type'), table_name='omega_miya_entity')
    op.drop_index(op.f('ix_omega_miya_entity_entity_name'), table_name='omega_miya_entity')
    op.drop_index(op.f('ix_omega_miya_entity_entity_id'), table_name='omega_miya_entity')
    op.drop_table('omega_miya_entity')
    op.drop_index(op.f('ix_omega_miya_word_bank_reply_entity'), table_name='omega_miya_word_bank')
    op.drop_index(op.f('ix_omega_miya_word_bank_key_word'), table_name='omega_miya_word_bank')
    op.drop_index(op.f('ix_omega_miya_word_bank_id'), table_name='omega_miya_word_bank')
    op.drop_table('omega_miya_word_bank')
    op.drop_index(op.f('ix_omega_miya_system_setting_setting_value'), table_name='omega_miya_system_setting')
    op.drop_index(op.f('ix_omega_miya_system_setting_setting_name'), table_name='omega_miya_system_setting')
    op.drop_index(op.f('ix_omega_miya_system_setting_setting_key'), table_name='omega_miya_system_setting')
    op.drop_table('omega_miya_system_setting')
    op.drop_index(op.f('ix_omega_miya_subscription_source_sub_type'), table_name='omega_miya_subscription_source')
    op.drop_index(op.f('ix_omega_miya_subscription_source_sub_id'), table_name='omega_miya_subscription_source')
    op.drop_index(op.f('ix_omega_miya_subscription_source_id'), table_name='omega_miya_subscription_source')
    op.drop_table('omega_miya_subscription_source')
    op.drop_index(op.f('ix_omega_miya_statistic_plugin_name'), table_name='omega_miya_statistic')
    op.drop_index(op.f('ix_omega_miya_statistic_parent_entity_id'), table_name='omega_miya_statistic')
    op.drop_index(op.f('ix_omega_miya_statistic_module_name'), table_name='omega_miya_statistic')
    op.drop_index(op.f('ix_omega_miya_statistic_id'), table_name='omega_miya_statistic')
    op.drop_index(op.f('ix_omega_miya_statistic_entity_id'), table_name='omega_miya_statistic')
    op.drop_index(op.f('ix_omega_miya_statistic_call_time'), table_name='omega_miya_statistic')
    op.drop_index(op.f('ix_omega_miya_statistic_bot_self_id'), table_name='omega_miya_statistic')
    op.drop_table('omega_miya_statistic')
    op.drop_index(op.f('ix_omega_miya_social_media_content_title'), table_name='omega_miya_social_media_content')
    op.drop_index(op.f('ix_omega_miya_social_media_content_source'), table_name='omega_miya_social_media_content')
    op.drop_index(op.f('ix_omega_miya_social_media_content_m_uid'), table_name='omega_miya_social_media_content')
    op.drop_index(op.f('ix_omega_miya_social_media_content_m_type'), table_name='omega_miya_social_media_content')
    op.drop_index(op.f('ix_omega_miya_social_media_content_m_id'), table_name='omega_miya_social_media_content')
    op.drop_table('omega_miya_social_media_content')
    op.drop_index(op.f('ix_omega_miya_plugin_plugin_name'), table_name='omega_miya_plugin')
    op.drop_index(op.f('ix_omega_miya_plugin_module_name'), table_name='omega_miya_plugin')
    op.drop_index(op.f('ix_omega_miya_plugin_enabled'), table_name='omega_miya_plugin')
    op.drop_table('omega_miya_plugin')
    op.drop_index(op.f('ix_omega_miya_message_history_user_entity_id'), table_name='omega_miya_message_history')
    op.drop_index(op.f('ix_omega_miya_message_history_received_time'), table_name='omega_miya_message_history')
    op.drop_index(op.f('ix_omega_miya_message_history_message_type'), table_name='omega_miya_message_history')
    op.drop_index(op.f('ix_omega_miya_message_history_message_id'), table_name='omega_miya_message_history')
    op.drop_index(op.f('ix_omega_miya_message_history_id'), table_name='omega_miya_message_history')
    op.drop_index(op.f('ix_omega_miya_message_history_event_entity_id'), table_name='omega_miya_message_history')
    op.drop_index(op.f('ix_omega_miya_message_history_bot_self_id'), table_name='omega_miya_message_history')
    op.drop_table('omega_miya_message_history')
    op.drop_index(op.f('ix_omega_miya_global_cache_expired_at'), table_name='omega_miya_global_cache')
    op.drop_index(op.f('ix_omega_miya_global_cache_cache_name'), table_name='omega_miya_global_cache')
    op.drop_index(op.f('ix_omega_miya_global_cache_cache_key'), table_name='omega_miya_global_cache')
    op.drop_table('omega_miya_global_cache')
    op.drop_index(op.f('ix_omega_miya_bots_self_id'), table_name='omega_miya_bots')
    op.drop_index(op.f('ix_omega_miya_bots_id'), table_name='omega_miya_bots')
    op.drop_index(op.f('ix_omega_miya_bots_bot_type'), table_name='omega_miya_bots')
    op.drop_table('omega_miya_bots')
    op.drop_index(op.f('ix_omega_miya_artwork_collection_width'), table_name='omega_miya_artwork_collection')
    op.drop_index(op.f('ix_omega_miya_artwork_collection_uname'), table_name='omega_miya_artwork_collection')
    op.drop_index(op.f('ix_omega_miya_artwork_collection_uid'), table_name='omega_miya_artwork_collection')
    op.drop_index(op.f('ix_omega_miya_artwork_collection_title'), table_name='omega_miya_artwork_collection')
    op.drop_index(op.f('ix_omega_miya_artwork_collection_rating'), table_name='omega_miya_artwork_collection')
    op.drop_index(op.f('ix_omega_miya_artwork_collection_origin'), table_name='omega_miya_artwork_collection')
    op.drop_index(op.f('ix_omega_miya_artwork_collection_height'), table_name='omega_miya_artwork_collection')
    op.drop_index(op.f('ix_omega_miya_artwork_collection_classification'), table_name='omega_miya_artwork_collection')
    op.drop_index(op.f('ix_omega_miya_artwork_collection_aid'), table_name='omega_miya_artwork_collection')
    op.drop_table('omega_miya_artwork_collection')
    # ### end Alembic commands ###
