"""init_baseline_20260828

Revision ID: 69d603c01e0e
Revises: 
Create Date: 2026-08-30 13:45:29.353145

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69d603c01e0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('omega_miya_artwork_collection',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=False, comment='作品来源/收录站点'),
    sa.Column('aid', sa.String(length=64), nullable=False, comment='作品原始ID/收录站点ID'),
    sa.Column('uid', sa.String(length=64), nullable=False, comment='作者ID'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('uname', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.SmallInteger(), nullable=False, comment='-2=忽略, -1=未知, 0=未分类, 1=AI生成, 2=外部来源, 3=人工分类'),
    sa.Column('rating', sa.SmallInteger(), nullable=False, comment='-1=Unknown, 0=G, 1=S, 2=Q, 3=E'),
    sa.Column('width', sa.Integer(), nullable=False, comment='原始图片宽度'),
    sa.Column('height', sa.Integer(), nullable=False, comment='原始图片高度'),
    sa.Column('orientation', sa.SmallInteger(), nullable=False, comment='宽高方位, 1=横图 0=方图 -1=竖图'),
    sa.Column('url', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False, comment='作品在该来源/收录站点的访问地址'),
    sa.Column('source', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='作品原始出处地址'),
    sa.Column('cover_page', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='作品首页/封面图片链接'),
    sa.Column('raw_tags', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_artwork_collection')),
    sa.UniqueConstraint('origin', 'aid', name=op.f('uq_omega_miya_artwork_collection_origin')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_artwork_collection', schema=None) as batch_op:
        batch_op.create_index('ix_artwork_classification_rating', ['classification', 'rating'], unique=False)
        batch_op.create_index('ix_artwork_common_search', ['origin', 'classification', 'rating', 'orientation'], unique=False)
        batch_op.create_index(batch_op.f('ix_omega_miya_artwork_collection_origin'), ['origin', 'uid'], unique=False)

    op.create_table('omega_miya_artwork_tag',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('tag_alt_name', sa.String(length=255), nullable=True, comment='Tag的别名或翻译名'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_artwork_tag')),
    sa.UniqueConstraint('tag_name', name=op.f('uq_omega_miya_artwork_tag_tag_name')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('omega_miya_bot',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('bot_type', sa.String(length=64), nullable=False),
    sa.Column('self_id', sa.String(length=64), nullable=False),
    sa.Column('bot_status', sa.SmallInteger(), nullable=False),
    sa.Column('bot_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_bot')),
    sa.UniqueConstraint('bot_type', 'self_id', name=op.f('uq_omega_miya_bot_bot_type')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('omega_miya_global_cache',
    sa.Column('cache_name', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('cache_value', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_name', 'cache_key', name=op.f('pk_omega_miya_global_cache')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_global_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_global_cache_expired_at'), ['expired_at'], unique=False)

    op.create_table('omega_miya_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('received_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('bot_self_id', sa.String(length=64), nullable=False),
    sa.Column('event_entity_id', sa.String(length=64), nullable=False),
    sa.Column('user_entity_id', sa.String(length=64), nullable=False),
    sa.Column('message_type', sa.String(length=64), nullable=False),
    sa.Column('message_plain_text', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('message_raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_history')),
    sa.UniqueConstraint('bot_self_id', 'message_id', name=op.f('uq_omega_miya_history_bot_self_id')),
    sa.UniqueConstraint('message_id', 'bot_self_id', 'event_entity_id', 'user_entity_id', name=op.f('uq_omega_miya_history_message_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_history_bot_self_id'), ['bot_self_id', 'event_entity_id', 'user_entity_id', 'message_type', 'received_timestamp'], unique=False)

    op.create_table('omega_miya_plugin',
    sa.Column('plugin_name', sa.String(length=255), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.SmallInteger(), nullable=False),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('plugin_name', 'module_name', name=op.f('pk_omega_miya_plugin')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_plugin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_plugin_enabled'), ['enabled'], unique=False)

    op.create_table('omega_miya_social_media_content',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False, comment='出处平台'),
    sa.Column('m_type', sa.String(length=64), nullable=False, comment='内容原始类型'),
    sa.Column('m_id', sa.String(length=64), nullable=False, comment='内容原始ID'),
    sa.Column('m_uid', sa.String(length=64), nullable=False, comment='内容发布者ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='内容标题'),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='内容文本'),
    sa.Column('ref_content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='引用/转发内容文本'),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_social_media_content')),
    sa.UniqueConstraint('source', 'm_type', 'm_id', name=op.f('uq_omega_miya_social_media_content_source')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_social_media_content', schema=None) as batch_op:
        batch_op.create_index('ix_social_media_content_uid_search', ['source', 'm_type', 'm_uid'], unique=False)

    op.create_table('omega_miya_statistic',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('plugin_name', sa.String(length=255), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('call_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('call_entity_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('call_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_statistic')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_statistic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_statistic_call_timestamp'), ['call_timestamp', 'plugin_name', 'module_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_omega_miya_statistic_plugin_name'), ['plugin_name', 'module_name', 'call_timestamp'], unique=False)

    op.create_table('omega_miya_subscription_source',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('sub_type', sa.String(length=64), nullable=False, comment='订阅类型'),
    sa.Column('sub_id', sa.String(length=64), nullable=False, comment='订阅id，直播间房间号/用户uid等'),
    sa.Column('sub_user_name', sa.String(length=64), nullable=False, comment='订阅用户的名称'),
    sa.Column('sub_info', sa.String(length=255), nullable=True, comment='订阅源信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_subscription_source')),
    sa.UniqueConstraint('sub_type', 'sub_id', name=op.f('uq_omega_miya_subscription_source_sub_type')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('omega_miya_system_setting',
    sa.Column('setting_name', sa.String(length=64), nullable=False),
    sa.Column('setting_key', sa.String(length=64), nullable=False),
    sa.Column('setting_value', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('setting_name', 'setting_key', name=op.f('pk_omega_miya_system_setting')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('omega_miya_artwork_review_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('artwork_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('review_timestamp', sa.BigInteger(), nullable=False, comment='评审时间戳'),
    sa.Column('review_classification', sa.SmallInteger(), nullable=False, comment='评审分类结果'),
    sa.Column('review_rating', sa.SmallInteger(), nullable=False, comment='评审分级结果'),
    sa.Column('review_from', sa.String(length=255), nullable=False, comment='评审来源'),
    sa.Column('review_info', sa.String(length=255), nullable=False, comment='评审附加信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_index_id'], ['omega_miya_artwork_collection.id'], name=op.f('fk_omega_miya_artwork_review_records_artwork_index_id_omega_miya_artwork_collection'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_artwork_review_records')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_artwork_review_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_artwork_review_records_artwork_index_id'), ['artwork_index_id', 'review_timestamp'], unique=False)

    op.create_table('omega_miya_artwork_with_tags',
    sa.Column('artwork_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('tag_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_index_id'], ['omega_miya_artwork_collection.id'], name=op.f('fk_omega_miya_artwork_with_tags_artwork_index_id_omega_miya_artwork_collection'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_index_id'], ['omega_miya_artwork_tag.id'], name=op.f('fk_omega_miya_artwork_with_tags_tag_index_id_omega_miya_artwork_tag'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artwork_index_id', 'tag_index_id', name=op.f('pk_omega_miya_artwork_with_tags')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_artwork_with_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_artwork_with_tags_tag_index_id'), ['tag_index_id', 'artwork_index_id'], unique=False)

    op.create_table('omega_miya_entity',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('bot_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False, comment='实体类型'),
    sa.Column('entity_id', sa.String(length=64), nullable=False, comment='实体平台ID'),
    sa.Column('entity_name', sa.String(length=64), nullable=False, comment='实体名称'),
    sa.Column('entity_info', sa.String(length=255), nullable=True, comment='实体描述信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_index_id'], ['omega_miya_bot.id'], name=op.f('fk_omega_miya_entity_bot_index_id_omega_miya_bot'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_entity')),
    sa.UniqueConstraint('bot_index_id', 'entity_type', 'entity_id', name=op.f('uq_omega_miya_entity_bot_index_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_entity_entity_type'), ['entity_type', 'entity_id'], unique=False)

    op.create_table('omega_miya_auth_setting',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('entity_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=False, comment='配置模块名称'),
    sa.Column('plugin', sa.String(length=255), nullable=False, comment='配置插件名称'),
    sa.Column('node', sa.String(length=64), nullable=False, comment='权限节点/配置名'),
    sa.Column('available', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'], name=op.f('fk_omega_miya_auth_setting_entity_index_id_omega_miya_entity'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_auth_setting')),
    sa.UniqueConstraint('entity_index_id', 'module', 'plugin', 'node', name=op.f('uq_omega_miya_auth_setting_entity_index_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_auth_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_auth_setting_module'), ['module', 'plugin', 'node', 'available'], unique=False)

    op.create_table('omega_miya_cooldown',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('entity_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False, comment='冷却事件, 用于唯一标识某个/类冷却'),
    sa.Column('stop_at', sa.DateTime(), nullable=False, comment='冷却结束时间'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='事件描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'], name=op.f('fk_omega_miya_cooldown_entity_index_id_omega_miya_entity'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_cooldown')),
    sa.UniqueConstraint('entity_index_id', 'event', name=op.f('uq_omega_miya_cooldown_entity_index_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_cooldown', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_cooldown_event'), ['event', 'stop_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_omega_miya_cooldown_stop_at'), ['stop_at', 'event'], unique=False)

    op.create_table('omega_miya_friendship',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('entity_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False, comment='当前状态'),
    sa.Column('mood', sa.Numeric(precision=6, scale=2), nullable=False, comment='情绪值'),
    sa.Column('friendship', sa.Numeric(precision=18, scale=4), nullable=False, comment='好感度'),
    sa.Column('energy', sa.Numeric(precision=18, scale=4), nullable=False, comment='能量值'),
    sa.Column('currency', sa.Numeric(precision=18, scale=4), nullable=False, comment='持有货币'),
    sa.Column('rsp_threshold', sa.Numeric(precision=6, scale=2), nullable=False, comment='响应阈值'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'], name=op.f('fk_omega_miya_friendship_entity_index_id_omega_miya_entity'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_friendship')),
    sa.UniqueConstraint('entity_index_id', name=op.f('uq_omega_miya_friendship_entity_index_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('omega_miya_sign_in',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('entity_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('sign_in_date', sa.Date(), nullable=False, comment='签到日期'),
    sa.Column('sign_in_info', sa.String(length=64), nullable=True, comment='签到信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'], name=op.f('fk_omega_miya_sign_in_entity_index_id_omega_miya_entity'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omega_miya_sign_in')),
    sa.UniqueConstraint('entity_index_id', 'sign_in_date', name=op.f('uq_omega_miya_sign_in_entity_index_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_sign_in', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_sign_in_sign_in_date'), ['sign_in_date', 'entity_index_id'], unique=False)

    op.create_table('omega_miya_subscription',
    sa.Column('sub_source_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('entity_index_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('sub_info', sa.String(length=255), nullable=True, comment='订阅信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_index_id'], ['omega_miya_entity.id'], name=op.f('fk_omega_miya_subscription_entity_index_id_omega_miya_entity'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_source_index_id'], ['omega_miya_subscription_source.id'], name=op.f('fk_omega_miya_subscription_sub_source_index_id_omega_miya_subscription_source'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sub_source_index_id', 'entity_index_id', name=op.f('pk_omega_miya_subscription')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('omega_miya_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omega_miya_subscription_entity_index_id'), ['entity_index_id', 'sub_source_index_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('omega_miya_subscription', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_omega_miya_subscription_sub_source_index_id_omega_miya_subscription_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_omega_miya_subscription_entity_index_id_omega_miya_entity'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_omega_miya_subscription_entity_index_id'))

    op.drop_table('omega_miya_subscription')
    with op.batch_alter_table('omega_miya_sign_in', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_sign_in_sign_in_date'))

    op.drop_table('omega_miya_sign_in')
    op.drop_table('omega_miya_friendship')
    with op.batch_alter_table('omega_miya_cooldown', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_cooldown_stop_at'))
        batch_op.drop_index(batch_op.f('ix_omega_miya_cooldown_event'))

    op.drop_table('omega_miya_cooldown')
    with op.batch_alter_table('omega_miya_auth_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_auth_setting_module'))

    op.drop_table('omega_miya_auth_setting')
    with op.batch_alter_table('omega_miya_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_entity_entity_type'))

    op.drop_table('omega_miya_entity')
    with op.batch_alter_table('omega_miya_artwork_with_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_omega_miya_artwork_with_tags_tag_index_id_omega_miya_artwork_tag'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_omega_miya_artwork_with_tags_artwork_index_id_omega_miya_artwork_collection'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_omega_miya_artwork_with_tags_tag_index_id'))

    op.drop_table('omega_miya_artwork_with_tags')
    with op.batch_alter_table('omega_miya_artwork_review_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_omega_miya_artwork_review_records_artwork_index_id_omega_miya_artwork_collection'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_omega_miya_artwork_review_records_artwork_index_id'))

    op.drop_table('omega_miya_artwork_review_records')
    op.drop_table('omega_miya_system_setting')
    op.drop_table('omega_miya_subscription_source')
    with op.batch_alter_table('omega_miya_statistic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_statistic_plugin_name'))
        batch_op.drop_index(batch_op.f('ix_omega_miya_statistic_call_timestamp'))

    op.drop_table('omega_miya_statistic')
    with op.batch_alter_table('omega_miya_social_media_content', schema=None) as batch_op:
        batch_op.drop_index('ix_social_media_content_uid_search')

    op.drop_table('omega_miya_social_media_content')
    with op.batch_alter_table('omega_miya_plugin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_plugin_enabled'))

    op.drop_table('omega_miya_plugin')
    with op.batch_alter_table('omega_miya_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_history_bot_self_id'))

    op.drop_table('omega_miya_history')
    with op.batch_alter_table('omega_miya_global_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_global_cache_expired_at'))

    op.drop_table('omega_miya_global_cache')
    op.drop_table('omega_miya_bot')
    op.drop_table('omega_miya_artwork_tag')
    with op.batch_alter_table('omega_miya_artwork_collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_artwork_collection_origin'))
        batch_op.drop_index('ix_artwork_common_search')
        batch_op.drop_index('ix_artwork_classification_rating')

    op.drop_table('omega_miya_artwork_collection')
    # ### end Alembic commands ###
