"""modify_constraints_20260903

Revision ID: da461cbe08d0
Revises: 69d603c01e0e
Create Date: 2026-09-03 15:46:33.797526

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da461cbe08d0'
down_revision: Union[str, Sequence[str], None] = '69d603c01e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('omega_miya_artwork_collection', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('ck_omega_miya_artwork_collection_classification'), 'classification BETWEEN -2 AND 3')
        batch_op.create_check_constraint(batch_op.f('ck_omega_miya_artwork_collection_rating'), 'rating BETWEEN -1 AND 3')

    with op.batch_alter_table('omega_miya_artwork_review_records', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('ck_omega_miya_artwork_review_records_review_classification'), 'review_classification BETWEEN -2 AND 3')
        batch_op.create_check_constraint(batch_op.f('ck_omega_miya_artwork_review_records_review_rating'), 'review_rating BETWEEN -1 AND 3')

    with op.batch_alter_table('omega_miya_bot', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('ck_omega_miya_bot_bot_status'), 'bot_status BETWEEN -1 AND 1')

    with op.batch_alter_table('omega_miya_history', schema=None) as batch_op:
        # 注意: uq_omega_miya_history_message_id 是内联 UNIQUE 约束而非独立索引,
        # SQLite 下不存在同名索引, 必须使用 drop_constraint 由 Alembic 按方言处理
        # (MySQL 翻译为 DROP INDEX, SQLite 通过 batch 模式重建表移除该约束)
        batch_op.drop_constraint(batch_op.f('uq_omega_miya_history_message_id'), type_='unique')

    with op.batch_alter_table('omega_miya_plugin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omega_miya_plugin_enabled'))
        batch_op.create_check_constraint(batch_op.f('ck_omega_miya_plugin_enabled'), 'enabled BETWEEN -1 AND 1')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('omega_miya_plugin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_omega_miya_plugin_enabled'), type_='check')
        batch_op.create_index(batch_op.f('ix_omega_miya_plugin_enabled'), ['enabled'], unique=False)

    with op.batch_alter_table('omega_miya_history', schema=None) as batch_op:
        # 恢复命名 UNIQUE 约束(而非裸索引), 保持与基线定义一致, 避免 schema 漂移
        batch_op.create_unique_constraint(
            batch_op.f('uq_omega_miya_history_message_id'),
            ['message_id', 'bot_self_id', 'event_entity_id', 'user_entity_id'],
        )

    with op.batch_alter_table('omega_miya_bot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_omega_miya_bot_bot_status'), type_='check')

    with op.batch_alter_table('omega_miya_artwork_review_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_omega_miya_artwork_review_records_review_rating'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_omega_miya_artwork_review_records_review_classification'), type_='check')

    with op.batch_alter_table('omega_miya_artwork_collection', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_omega_miya_artwork_collection_rating'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_omega_miya_artwork_collection_classification'), type_='check')

    # ### end Alembic commands ###
